version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: instaloan-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: instaloan
      POSTGRES_PASSWORD: instaloan
      POSTGRES_DB: instaloan
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
